version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
        JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
        JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
        JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
        JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT}
        JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
    networks:
      - journey
  
  postgres:
    container_name: api-db
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: ${JOURNEY_DATABASE_USER}
        POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
        POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
    networks:
    - journey

networks:
  journey:
   driver: bridge