name: CI

on:
  push:
   branches:  
     - main
jobs:
  build-and-push:
   name: 'Build and Push'
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login into container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          iuriramos93/journey-devops:${{steps.generate_sha.outputs.sha}} 
          iuriramos93/journey-devops:latest



    # - name: Build Docker Image
    #   run: docker build -t iuriramos93/journey-devops:${{steps.generate_sha.outputs.sha}} .

    # - name: Push Image
    #   run: |
    #     docker push iuriramos93/journey-devops:${{steps.generate_sha.outputs.sha}}
    #     docker tag iuriramos93/journey-devops:${{steps.generate_sha.outputs.sha}} iuriramos93/journey-devops:latest
    #     docker push iuriramos93/journey-devops:latest

